[package]
name = "cli-password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
inline_colorization = "0.1.6"
rage = "0.11.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
